### ISSUE TITLE
'attention_net' is not defined

### ISSUE THREAD

**Issue by cahya-wirawan** [muellerzr/fastai_nts_net#1]
Hi,
Thanks for the repo. I tried the notebook PETS.ipynb, but I get following error:
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-26-46abe5e3d7ff> in <module>
----> 1 net = attention_net(6, data.c, 4, pretrained=True)

NameError: name 'attention_net' is not defined

```

attention_net is not defined anywhere anymore in your code. Maybe your latest code is not pushed to github yet?

**Comment by muellerzr** [comment]
Fixed the example notebook. It is called via NTSNet, pass in the databunch, a body, and everything else is the same.
